### ISSUE TITLE
Peer-to-peer-morning-session-reviews

### ISSUE THREAD

**Issue by mutugi-c** [naanmohammed/my-portfolio#4]
- A nicely done website. However, kindly remember to include "alt" in your images to ensure that your website information is well-accessible.

**Comment by fredo509** [comment]
Great job 💯 , kindly add `p` tag for a an description block 👍

**Comment by Ruthmy** [comment]
Hi Naan! Your website turned out great, you've done a great job. 
My only recommendation to you would be to use semantic HTML tags like `<section>` instead of `<div>` to divide the sections of your page (recent works, about me, etc.). In this way, you make use of good practices and help improve SEO.

**Comment by naanmohammed** [comment]
Thank you @mutugi-c @fredo509 @Ruthmy  for your great suggestions. I will update the code as per your suggestions.
Thank you again!
